services:
  api:
    container_name: itoi-api
    image: itoi
    environment:
      NODE_ENV: production
      ITOI_PROD: DEV
      DATABASE_URL: postgres://postgres:postgres@db:5432/itlingo
      ITLINGO_CLOUD_URL: http://localhost:8069/
      COM_KEY: "v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)J"
      COOKIE_KEY: "0JWVNoq6y7X8hai2r59YY8ILAxC8wcvGODtGvEkv2yKgxlVPfpCeUGqHsoxObdXV"
    ports:
      - 3000:3000
    expose:
      - "3000"
    volumes:
      - './:/home/theia/projectos'
volumes:
  db:
    driver: local
